RUN apk upgrade --no-cache && \
    apk add --no-cache \
    acl \
    autoconf \
    autoconf-archive \
    automake \
    bash \
    cmocka-dev \
    coreutils \
    curl-dev \
    dbus \
    dbus-dev \
    dbus-x11 \
    expect \
    g++ \
    gawk \
    gcc \
    git \
    glib-dev \
    gnutls-dev \
    grep \
    gzip \
    iproute2 \
    json-c-dev  \
    json-glib-dev \
    libftdi1-dev \
    libqrencode-dev \
    libseccomp-dev \
    libtasn1-dev \
    libtool \
    libusb-dev \
    m4 \
    make \
    net-tools \
    oath-toolkit-dev \
    opensc \
    openssl \
    openssl-dev \
    perl-utils \
    procps \
    py3-yaml \
    python3-dev \
    sed \
    socat \
    tar \
    uthash-dev \
    wget \
    yaml-dev
