RUN dnf -y install \
    acl \
    autoconf-archive \
    automake \
    crypto-policies-scripts \
    dbus-devel \
    dbus-libs \
    dbus-x11 \
    expect \
    gawk \
    gcc \
    git \
    glib2-devel \
    gmp-devel \
    gnulib \
    gnutls-utils \
    iproute \
    json-c-devel \
    json-glib-devel \
    libasan \
    libcmocka \
    libcmocka-devel \
    libcurl-devel \
    libftdi-devel \
    libgcrypt-devel \
    libseccomp-devel \
    libtpms-devel \
    libsq3-devel \
    libtasn1-devel \
    libtool \
    libubsan \
    libusb1-devel \
    libuuid-devel \
    libyaml-devel \
    m4 \
    net-tools \
    opensc \
    openssl \
    openssl-devel \
    perl-Digest-SHA \
    pkg-config \
    procps \
    python3-devel \
    socat \
    swtpm \
    uthash-devel \
    wget \
    && update-crypto-policies --set=LEGACY \
    && dnf clean all && rm -rf /var/cache/dnf
