RUN zypper ref
RUN zypper -n in \
    acl \
    autoconf \
    autoconf-archive \
    automake \
    curl \
    dbus-1-devel \
    dbus-1-x11 \
    expect \
    gawk \
    gcc \
    gcc-c++ \
    git \
    glib2-devel \
    gmp-devel \
    gnutls \
    gzip \
    iproute \
    json-glib-devel \
    libcmocka-devel \
    libcurl-devel \
    libftdi1-devel \
    libgcrypt-devel \
    libjson-c-devel \
    libseccomp-devel \
    libtasn1-devel \
    libtool \
    libusb-devel \
    libuuid-devel \
    libyaml-devel \
    m4 \
    net-tools \
    net-tools-deprecated \
    opensc \
    openssh-common \
    openssl-devel \
    pkg-config \
    socat \
    sqlite3 \
    sqlite3-devel \
    wget \
    which \
    xz \
    && zypper clean --all
