#
# Build Docker Images for both pull_request and push operations
#
name: Build Status
on:
  [ pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  generate-matrix:
    runs-on: ubuntu-latest

    outputs:
      distros: ${{ steps.set-matrix.outputs.distros }}

    steps:
      - uses: actions/checkout@v7

      - id: set-matrix
        run: |
          DISTROS=$(find . -maxdepth 1 -name '*.docker.m4' \
            | sed 's|^\./||' \
            | sed 's|\.docker\.m4$||' \
            | jq -R -s -c 'split("\n")[:-1]')

          echo "distros=$DISTROS" >> $GITHUB_OUTPUT

  build-image:
    name: Build Docker Images
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ${{ fromJson(needs.generate-matrix.outputs.distros) }}
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v7
      -
        id: changes
        name: Check Diff for Changes
        uses: dorny/paths-filter@v4
        with:
          filters: |
            build:
              - ${{ matrix.distro }}.docker.m4
              - modules/*
      -
        name: Build the Dockerfiles
        run: make -j $(nproc)
        if: steps.changes.outputs.build == 'true'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        if: steps.changes.outputs.build == 'true'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        if: steps.changes.outputs.build == 'true'
      -
        name: Build Docker Images
        uses: docker/build-push-action@v7
        with:
          push: false
          context: .
          file: ./${{ matrix.distro }}.docker
        if: steps.changes.outputs.build == 'true'
