name: Manual Publish
on:
  workflow_dispatch:
    inputs:
      distro:
        description: 'The distro to build and publish'
        type: string
        required: true
jobs:
  publish-image:
    name: Manual Publish Docker Images
    runs-on: ubuntu-latest
    if: "github.repository_owner == 'tpm2-software'"
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Build the Dockerfiles
        run: make -j $(nproc)
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.CR_PAT }}
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./${{ inputs.distro }}.docker
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.distro }}:latest

