#
# We only publish docker files on a push AND if the tpm2-software is the org.
# This way forks don't try to build AND publish
#
name: Publish
on:
  workflow_dispatch
    inputs:
      distro:
        description: 'The distro to build and publish'
        required: true
jobs:
  publish-image:
    name: Manual Publish Docker Images
    runs-on: ubuntu-latest
    if: "github.repository_owner == 'tpm2-software'"
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Build the Dockerfiles
        run: make -j $(nproc)
      -
        name: Setup QEMU
        run: |
          sudo apt-get update
          sudo apt-get install qemu binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./${{ inputs.distro }}.docker
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.distro }}:latest

