#
# We only publish docker files on a push AND if the tpm2-software is the org.
# This way forks don't try to build AND publish
#
name: Publish
on:
  [ push, workflow_dispatch]
jobs:
  publish-image:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [
          "fedora-30", "fedora-32", "fedora-34",
          "opensuse-leap-15.2", "opensuse-leap",
          "ubuntu-18.04", "ubuntu-20.04",
          "ubuntu-20.04.arm32v7", "ubuntu-20.04.arm64v8",
          "fedora-32.ppc64le",
          "alpine-3.15",
          "ubuntu-20.04-ossl3", "ubuntu-22.04", "ubuntu-22.04-mbedtls-3.1"
        ]
    if: "github.repository_owner == 'tpm2-software'"
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Check Diff for Changes
        uses: technote-space/get-diff-action@v6
        with:
          FILES: |
            ${{ matrix.distro }}.docker.m4
          PATTERNS: |
            modules/*
      -
        name: Build the Dockerfiles
        run: make -j $(nproc)
        if: env.GIT_DIFF
      -
        name: Setup QEMU
        run: |
          sudo apt-get update
          sudo apt-get install qemu binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        if: env.GIT_DIFF
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: env.GIT_DIFF
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: env.GIT_DIFF
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./${{ matrix.distro }}.docker
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.distro }}:latest
        if: env.GIT_DIFF
