name: PRQ Status
on:
  pull_request
jobs:
  publish-image:
    name: Build and Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [
          "fedora-30", "fedora-32",
          "opensuse-leap-15.2", "opensuse-leap",
          "ubuntu-16.04", "ubuntu-18.04", "ubuntu-20.04",
          "ubuntu-20.04.arm32v7", "ubuntu-20.04.arm64v8",
          "fedora-32.ppc64le"
        ]
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Build the Dockerfiles
        run: make -j $(nproc)
      -
        name: Setup QEMU
        run: |
          sudo apt-get update
          sudo apt-get install qemu binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker Images
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: ./${{ matrix.distro }}.docker
